# Generated by Django 3.1.1 on 2020-10-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_hunter_favorite_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('rarity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='hunter',
            name='weapons',
            field=models.ManyToManyField(to='main_app.Weapon'),
        ),
    ]
